import React from "react";
import Head from "next/head";
import Header from "../../components/EventsPage/Header";
import EventHeader from "../../components/EventsPage/EventHeader";
import EventBanner from "../../components/EventsPage/EventBanner";
import EventBody from "../../components/EventsPage/EventBody";
import Footer from "../../components/Footer";

const Index = () => {
  return (
    <div>
      <Head>
        <title>Event Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className="overflow-x-hidden bg-[#1C1C1C]">
        <Header />
        <EventHeader />
        <EventBanner />
        <EventBody />
      </body>

      <Footer />
    </div>
  );
};

export default Index;
