import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Body from "../components/HomePage/Body";
import Footer from "../components/HomePage/Footer";
import { loginState } from "../recoil";
import { useRecoilState } from "recoil";
import { global } from "../global";
import { checkLoggedIn } from "../public/global";

export default function Home() {
  const [loginId, setLoginId] = useRecoilState(loginState);

  useEffect(() => {
    checkLoggedIn(setLoginId);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className={`bg-[${global.colors.primary}] min-h-screen`}>
        <Body />
      </div>
      <Footer />
    </>
  );
}
